# Generated by Django 2.1.7 on 2019-03-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tel', models.IntegerField(max_length=11)),
                ('age', models.IntegerField(max_length=3)),
                ('sex', models.BooleanField()),
                ('crt_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '博主资料',
                'db_table': 'AdminInfo',
            },
        ),
        migrations.CreateModel(
            name='viewpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=40, unique=True)),
                ('content', models.TextField(max_length=4400)),
                ('author', models.ForeignKey(on_delete=True, to='myblog.admin')),
            ],
            options={
                'verbose_name': '帖子',
                'db_table': 'viewpoint',
            },
        ),
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('open_id', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=3)),
                ('sex', models.BooleanField()),
            ],
            options={
                'verbose_name': '访客资料',
                'db_table': 'visitor',
            },
        ),
        migrations.CreateModel(
            name='visitorhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('historytime', models.DateTimeField()),
            ],
        ),
    ]
