# Generated by Django 2.1.7 on 2019-03-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190306_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorhistory',
            options={'verbose_name_plural': '访客记录'},
        ),
    ]
