# Generated by Django 2.1.7 on 2019-03-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190306_1009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='author',
        ),
    ]
