# Generated by Django 2.1.7 on 2019-03-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20190306_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
