# Generated by Django 2.1.7 on 2019-03-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20190306_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='tel',
            field=models.CharField(default='电话号码', max_length=11),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='age',
            field=models.IntegerField(),
        ),
    ]
